// Extraction sanity check on a real article.
const URL_ = process.argv[2] || "https://en.wikipedia.org/wiki/Speech_synthesis";
const v = await fetch("http://127.0.0.1:9222/json/version").then(r=>r.json());
const ws = new WebSocket(v.webSocketDebuggerUrl); await new Promise(r=>ws.onopen=r);
let id=0; const pend=new Map();
ws.onmessage = e => { const m=JSON.parse(e.data); if(m.id&&pend.has(m.id)){ const p=pend.get(m.id); pend.delete(m.id); m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result);} };
const send=(method,params={},sessionId)=>new Promise((res,rej)=>{pend.set(++id,{res,rej}); ws.send(JSON.stringify({id,method,params,sessionId}));});
const ev = async (sid, expression) => { const r = await send("Runtime.evaluate",{expression, awaitPromise:true, returnByValue:true}, sid); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text); return r.result.value; };
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const { targetInfos } = await send("Target.getTargets");
const off = targetInfos.find(t=>t.url.includes("/offscreen/offscreen.html"));
const EXT = new URL(off.url).host;
const { targetId } = await send("Target.createTarget",{url: URL_});
await sleep(5000);
const { sessionId: so } = await send("Target.attachToTarget",{targetId: off.targetId, flatten:true});
await ev(so, `chrome.runtime.sendMessage({target:'background', type:'cs:getState'}).catch(()=>{})`);
const { targetInfos: t2 } = await send("Target.getTargets");
const sw = t2.find(t=>t.type==="service_worker" && t.url.includes(EXT));
const { sessionId: ss } = await send("Target.attachToTarget",{targetId: sw.targetId, flatten:true});
const tabId = await ev(ss, `chrome.tabs.query({url: ${JSON.stringify(URL_.split("#")[0] + "*")}}).then(t=>t[0]?.id)`);
const t0 = performance.now();
const res = await ev(ss, `chrome.tabs.sendMessage(${tabId}, {type:'cs:getChunks', mode:'smart'})`);
const ms = performance.now()-t0;
const texts = res.chunks.map(c=>c.text);
console.log(`${texts.length} chunks in ${ms.toFixed(0)}ms (incl. messaging); total ${texts.join(" ").length} chars`);
console.log("--- first 12:"); texts.slice(0,12).forEach((t,i)=>console.log(i, JSON.stringify(t.slice(0,110))));
console.log("--- last 4:"); texts.slice(-4).forEach((t)=>console.log(JSON.stringify(t.slice(0,110))));
const bad = texts.filter(t=>/^\[?edit\]?$|^Jump to content|^Main menu|^Toggle the table|^Contents$/i.test(t));
console.log("suspicious chunks:", bad.length, bad.slice(0,5));
await send("Target.closeTarget",{targetId});
ws.close();
